version: "3.9"
services:
  server: # back-end nodejs api
    build: ./server
    restart: always
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10
    restart: always
    user: "108:108" # preserve /var/lib/mysql permissions on host machine
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true

  client: # front-end
    build: ./client
    restart: always
    ports:
      - "55533:80"  ## forward port 80 on docker to 55533 on local machine
    depends_on:
      - server
