version: "3.9"
services:
  server: # back-end nodejs api
    build: ./server
    restart: always
    # environment:
    #   - DB_SERVER="localhost:6379"

  client: # front-end vuejs
    build: ./client
    restart: always
    ports:
      - "55533:80"  ## forward port 80 on docker to 55533 on local machine
    depends_on:
      - server
