version: "3.9"
services:
  server: # back-end nodejs api
    build: ./server
    restart: always
    depends_on:
      - redis
    network_mode: host

  client: # front-end
    build: ./client
    restart: always
    # ports:
    #   - "55533:80"  ## forward port 80 on docker to 55533 on local machine
    depends_on:
      - server
    network_mode: host