version: "3.9"
services:
  server: # back-end nodejs api
    build: ./server
    restart: always
    depends_on:
      - database

  client: # front-end vuejs
    build: ./client
    restart: always
    ports:
      - "55533:80"  ## forward port 80 on docker to 55533 on local machine
    depends_on:
      - server

  database:
    image: neo4j
    restart: on-failure
    environment:
      - NEO4J_AUTH=neo4j/admin
    expose:
      - 7474
    volumes:
      - /var/lib/neo4j/import:/var/lib/neo4j/import ## static .csv files
      - /var/lib/neo4j/data:/data	## database data files
